import { urlToName } from "./lib/url";

export const SOURCE_CODE_GITHUB_REPO = "Aniket-508/twitter-followers-video";

export const SITE = {
  NAME: "Twitter Followers Video",
  URL: "https://followers.video",
  OG_IMAGE: "/og.png",
  DESCRIPTION:
    "Generate animated videos to celebrate & share your Twitter/X follower milestones.",
  AUTHOR: {
    NAME: "Aniket Pawar",
    URL: "https://www.aniketpawar.com",
    EMAIL: "pawaraniket508@gmail.com",
    TWITTER: "@alaymanguy",
  },
  KEYWORDS: [
    "twitter",
    "x",
    "followers",
    "video",
    "animation",
    "remotion",
    "social media",
    "milestone",
    "celebration",
  ],
} as const;

export const LINK = {
  TWITTER: "https://x.com/@alaymanguy",
  GITHUB: "https://github.com/Aniket-508",
  SPONSOR: "https://github.com/sponsors/Aniket-508",
  LICENSE: `https://github.com/${SOURCE_CODE_GITHUB_REPO}/blob/main/LICENSE`,
} as const;

export const UTM_PARAMS = {
  utm_source: urlToName(SITE.URL),
} as const;

export const RANDOM_NAMES = [
  "Liam",
  "Noah",
  "Oliver",
  "Elijah",
  "William",
  "James",
  "Benjamin",
  "Lucas",
  "Henry",
  "Alexander",
  "Olivia",
  "Emma",
  "Charlotte",
  "Amelia",
  "Sophia",
  "Isabella",
  "Ava",
  "Mia",
  "Evelyn",
  "Harper",
  "Mason",
  "Ethan",
  "Logan",
  "Jacob",
  "Michael",
  "Elijah",
  "Daniel",
  "Matthew",
  "Aiden",
  "Jackson",
  "Sebastian",
  "David",
  "Carter",
  "Wyatt",
  "Jayden",
  "John",
  "Owen",
  "Dylan",
  "Luke",
  "Gabriel",
  "Anthony",
  "Isaac",
  "Grayson",
  "Jack",
  "Julian",
  "Levi",
  "Christopher",
  "Joshua",
  "Andrew",
  "Lincoln",
  "Mateo",
  "Ryan",
  "Jaxon",
  "Nathan",
  "Aaron",
  "Isaiah",
  "Thomas",
  "Charles",
  "Caleb",
  "Josiah",
  "Christian",
  "Hunter",
  "Eli",
  "Jonathan",
  "Connor",
  "Landon",
  "Adrian",
  "Asher",
  "Cameron",
  "Leo",
  "Theodore",
  "Jeremiah",
  "Hudson",
  "Robert",
  "Easton",
  "Nolan",
  "Nicholas",
  "Ezra",
  "Colton",
  "Angel",
  "Brayden",
  "Jordan",
  "Dominic",
  "Austin",
  "Ian",
  "Adam",
  "Elias",
  "Jaxson",
  "Greyson",
  "Jose",
  "Ezekiel",
  "Carson",
  "Evan",
  "Maverick",
  "Bryson",
  "Jace",
  "Cooper",
  "Xavier",
  "Parker",
  "Roman",
  "Jason",
];
